const videoFormats=[['399','2160p','AV1','60 fps','412 MB'],['248','1080p','VP9','60 fps','238 MB'],['137','1080p','AVC','30 fps','226 MB'],['247','720p','VP9','60 fps','141 MB'],['136','720p','AVC','30 fps','126 MB']];
const audioFormats=[['251','160 kbps','Opus','48 kHz','10.8 MB'],['250','70 kbps','Opus','48 kHz','7.2 MB'],['140','128 kbps','AAC','44.1 kHz','8.4 MB']];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const toast=$('#toast');let timer;
function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),2600)}
function renderRows(target,rows,type){target.innerHTML=rows.map((r,i)=>`<tr><td><input type="radio" name="${type}-format" value="${r[0]}" ${i===0?'checked':''}></td><td>${r[0]}</td><td class="format-quality">${r[1]}</td><td><span class="codec">${r[2]}</span></td><td>${r[3]}</td><td>${r[4]}</td></tr>`).join('')}
function renderFormats(){renderRows($('#video-rows'),videoFormats,'video');renderRows($('#audio-rows'),audioFormats,'audio');$('#video-count').textContent=`视频 ${videoFormats.length}`;$('#audio-count').textContent=`音频 ${audioFormats.length}`}
function selectView(view){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${view}-view`))}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>selectView(b.dataset.view)));$$('[data-view-target]').forEach(b=>b.addEventListener('click',()=>selectView(b.dataset.viewTarget)));
$$('.source-btn').forEach(btn=>btn.addEventListener('click',()=>{$$('.source-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const yt=btn.dataset.platform==='youtube';$('#url').placeholder=yt?'粘贴 YouTube 视频链接':'粘贴 B站视频链接';$('#cookie-hint').textContent=`将使用 ${yt?'YouTube':'B站'} Cookie 配置`}));
$('#parse-btn').addEventListener('click',()=>{if(!$('#url').value.trim()){$('#url').focus();showToast('请先输入媒体地址');return}renderFormats();showToast(`解析完成：抓到 ${videoFormats.length} 个视频流、${audioFormats.length} 个音频流`)});
$$('[data-select]').forEach(b=>b.addEventListener('click',()=>{const input=$(`input[name="${b.dataset.select}-format"]`);if(!input){showToast('请先解析媒体地址');return}input.checked=true;showToast(`已选最高${b.dataset.select==='video'?'画质':'音质'}`)}));
function queueMode(){return $('#queue-mode').checked}function actionMessage(kind){const meta=$('#metadata').checked?'，保存元数据':'';const queued=queueMode();const map={best:'最高画质与音质将下载并合并',video:'最高画质视频流已准备下载',audio:'最高音质音频流已准备下载'};showToast(`${map[kind]}${meta}${queued?'，已加入下载列表':'，开始下载'}`);if(queued)selectView('queue');else{$('#progress-empty').classList.add('hidden');$('#progress-active').classList.remove('hidden')}}
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>actionMessage(b.dataset.action)));
$('#download-selected').addEventListener('click',()=>{if(!$('input[name="video-format"]:checked')&&!$('input[name="audio-format"]:checked')){showToast('请先解析并选择视频流或音频流');return}const v=$('input[name="video-format"]:checked'),a=$('input[name="audio-format"]:checked');actionMessage(v&&a?'best':v?'video':'audio')});
$('#queue-mode').addEventListener('change',e=>showToast(e.target.checked?'已打开：下载动作会先加入列表':'已关闭：下载动作将直接执行'));
$('#start-all').addEventListener('click',()=>showToast('下载队列已开始'));$('#clear-finished').addEventListener('click',()=>showToast('已清除已完成任务'));$$('.icon-btn').forEach(b=>b.addEventListener('click',()=>showToast(b.title+'：后端接入后生效')));$('#install-plugin').addEventListener('click',()=>$('#plugin-modal').classList.remove('hidden'));$('.plugin-install')?.addEventListener('click',()=>$('#plugin-modal').classList.remove('hidden'));function closePlugin(){ $('#plugin-modal').classList.add('hidden') }$('#close-plugin-modal').addEventListener('click',closePlugin);$('#cancel-plugin').addEventListener('click',closePlugin);$('#confirm-plugin').addEventListener('click',()=>{closePlugin();showToast($('#persist-plugin').checked?'插件已安装并持久化，需要重启下载服务':'插件已安装，需要重启下载服务')});$('#backup-now').addEventListener('click',()=>showToast('已生成备份（演示）'));$('#restore-backup').addEventListener('click',()=>showToast('请选择备份文件，再确认恢复内容'));$('#update-project').addEventListener('click',()=>showToast('项目更新检查将在后端接入'));$('#update-ytdlp').addEventListener('click',()=>showToast('yt-dlp 更新检查将在后端接入'));$('#clear-logs').addEventListener('click',()=>showToast('日志已清空'));
$$('.settings-tab').forEach(b=>b.addEventListener('click',()=>{$$('.settings-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.settings-section').forEach(x=>x.classList.remove('active'));$(`#${b.dataset.settings}-settings`).classList.add('active')}));$$('.save-btn').forEach(b=>b.addEventListener('click',()=>showToast('设置已保存到本地')));$$('.outline-btn').forEach(b=>b.addEventListener('click',()=>{if(b.textContent.includes('扫码')||b.textContent.includes('Cookie'))showToast(`${b.textContent.trim()}功能将在后端接入`)}));
let theme='system';function applyTheme(){document.body.classList.toggle('light',theme==='light'||(theme==='system'&&matchMedia('(prefers-color-scheme: light)').matches));$('#theme-label').textContent=theme==='system'?'跟随系统':theme==='light'?'浅色':'深色';$('#theme-toggle').title=`当前：${$('#theme-label').textContent}，点击切换`};$('#theme-toggle').addEventListener('click',()=>{theme=theme==='system'?'light':theme==='light'?'dark':'system';applyTheme()});applyTheme();
