let currentInfo=null;let currentPlatform='bilibili';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const toast=$('#toast');let timer;
function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),2600)}
function fmtSize(n){return n?`${(n/1048576).toFixed(1)} MB`:'--'}
function renderRows(target,rows,type){target.innerHTML=rows.map((r,i)=>`<tr><td><input type="radio" name="${type}-format" value="${r.id}" ${i===0?'checked':''}></td><td>${r.id}</td><td class="format-quality">${r.resolution||r.abr||'--'}</td><td><span class="codec">${type==='video'?(r.vcodec||'--'):(r.acodec||'--')}</span></td><td>${type==='video'?(r.fps?`${r.fps} fps`:'--'):(r.asr?`${r.asr} Hz`:'--')}</td><td>${fmtSize(r.size)}</td></tr>`).join('')||'<tr class="table-empty"><td colspan="6">没有可用流</td></tr>'}
function renderFormats(info){currentInfo=info;const v=info.formats.filter(x=>x.kind==='video'),a=info.formats.filter(x=>x.kind==='audio');renderRows($('#video-rows'),v,'video');renderRows($('#audio-rows'),a,'audio');$('#video-count').textContent=`视频 ${v.length}`;$('#audio-count').textContent=`音频 ${a.length}`}
function selectView(view){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${view}-view`))}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>selectView(b.dataset.view)));$$('[data-view-target]').forEach(b=>b.addEventListener('click',()=>selectView(b.dataset.viewTarget)));
$$('.source-btn').forEach(btn=>btn.addEventListener('click',()=>{$$('.source-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');currentPlatform=btn.dataset.platform;const yt=currentPlatform==='youtube';$('#url').placeholder=yt?'粘贴 YouTube 视频链接':'粘贴 B站视频链接';$('#cookie-hint').textContent=`将使用 ${yt?'YouTube':'B站'} Cookie 配置`}));
$('#parse-btn').addEventListener('click',async()=>{const url=$('#url').value.trim();if(!url){$('#url').focus();showToast('请先输入媒体地址');return}$('#parse-btn').disabled=true;$('#parse-btn').textContent='解析中…';try{const r=await fetch('/api/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,platform:currentPlatform})});const d=await r.json();if(!r.ok)throw Error(d.error||'解析失败');renderFormats(d);showToast(`解析完成：抓到 ${d.formats.filter(x=>x.kind==='video').length} 个视频流、${d.formats.filter(x=>x.kind==='audio').length} 个音频流`)}catch(e){showToast(e.message)}finally{$('#parse-btn').disabled=false;$('#parse-btn').innerHTML='⌕&nbsp; 开始解析'}});
$$('[data-select]').forEach(b=>b.addEventListener('click',()=>{const input=$(`input[name="${b.dataset.select}-format"]`);if(!input){showToast('请先解析媒体地址');return}input.checked=true;showToast(`已选最高${b.dataset.select==='video'?'画质':'音质'}`)}));
function queueMode(){return $('#queue-mode').checked}async function createJob(kind){if(!currentInfo){showToast('请先解析媒体地址');return}const v=$('input[name="video-format"]:checked'),a=$('input[name="audio-format"]:checked');const format=kind==='best'?(v&&a?`${v.value}+${a.value}`:v?.value||a?.value):kind==='video'?v?.value:a?.value;if(!format){showToast('请先选择对应的流');return}try{const r=await fetch('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:currentInfo.webpage_url||$('#url').value,format,title:currentInfo.title,platform:currentPlatform,metadata:$('#metadata').checked})});if(!r.ok)throw Error('任务创建失败');showToast(queueMode()?'已加入下载列表':'已提交下载任务');selectView('queue')}catch(e){showToast(e.message)}}
function actionMessage(kind){createJob(kind)}
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>actionMessage(b.dataset.action)));
$('#download-selected').addEventListener('click',()=>{const v=$('input[name="video-format"]:checked'),a=$('input[name="audio-format"]:checked');createJob(v&&a?'best':v?'video':'audio')});
$('#queue-mode').addEventListener('change',e=>showToast(e.target.checked?'已打开：下载动作会先加入列表':'已关闭：下载动作将直接执行'));
$('#start-all').addEventListener('click',()=>showToast('下载队列已开始'));$('#clear-finished').addEventListener('click',()=>showToast('已清除已完成任务'));$$('.icon-btn').forEach(b=>b.addEventListener('click',()=>showToast(b.title+'：后端接入后生效')));$('#install-plugin').addEventListener('click',()=>$('#plugin-modal').classList.remove('hidden'));$('.plugin-install')?.addEventListener('click',()=>$('#plugin-modal').classList.remove('hidden'));function closePlugin(){ $('#plugin-modal').classList.add('hidden') }$('#close-plugin-modal').addEventListener('click',closePlugin);$('#cancel-plugin').addEventListener('click',closePlugin);$('#confirm-plugin').addEventListener('click',()=>{closePlugin();showToast($('#persist-plugin').checked?'插件已安装并持久化，需要重启下载服务':'插件已安装，需要重启下载服务')});$('#backup-now').addEventListener('click',()=>showToast('已生成备份（演示）'));$('#restore-backup').addEventListener('click',()=>showToast('请选择备份文件，再确认恢复内容'));$('#update-project').addEventListener('click',()=>showToast('项目更新检查将在后端接入'));$('#update-ytdlp').addEventListener('click',()=>showToast('yt-dlp 更新检查将在后端接入'));$('#clear-logs').addEventListener('click',()=>showToast('日志已清空'));
$$('.settings-tab').forEach(b=>b.addEventListener('click',()=>{$$('.settings-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.settings-section').forEach(x=>x.classList.remove('active'));$(`#${b.dataset.settings}-settings`).classList.add('active')}));$$('.save-btn').forEach(b=>b.addEventListener('click',()=>showToast('设置已保存到本地')));$$('.outline-btn').forEach(b=>b.addEventListener('click',()=>{if(b.textContent.includes('扫码')||b.textContent.includes('Cookie'))showToast(`${b.textContent.trim()}功能将在后端接入`)}));
let theme='system';function applyTheme(){document.body.classList.toggle('light',theme==='light'||(theme==='system'&&matchMedia('(prefers-color-scheme: light)').matches));$('#theme-label').textContent=theme==='system'?'跟随系统':theme==='light'?'浅色':'深色';$('#theme-toggle').title=`当前：${$('#theme-label').textContent}，点击切换`};$('#theme-toggle').addEventListener('click',()=>{theme=theme==='system'?'light':theme==='light'?'dark':'system';applyTheme()});applyTheme();
